alias rspec='RAILS_ENV=test bundle exec rspec'
alias rails='bundle exec rails'
alias rake='bundle exec rake'
alias rubocop='bundle exec rubocop'
alias guard='bundle exec guard'
alias ls='ls --color=auto'
