x-ships-api-common:
  &ships-api-common
  build:
    context: .
    args:
      USERNAME: $USER
      UID: ${USER_ID:-0}
      GID: ${GROUP_ID:-0}
  volumes:
    - .:/app
    - ships-api-gems:/gems
    - /app/node_modules
  stdin_open: true # docker run -i
  tty: true        # docker run -t
  environment:
    DB_DEV: ships-api-development
    DB_HOST: db
    DB_TEST: ships-api-test
    DB_USERNAME: postgres
    REDIS_URL: redis://redis:6379

services:
  api:
    << : *ships-api-common
    command: "./script/start-dev.sh"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:11.5
    volumes:
      - ships-api-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

  sidekiq:
    << : *ships-api-common
    command: bundle exec sidekiq -r . -C config/sidekiq.yml
    depends_on:
      - db
      - redis
      - api

volumes:
  ships-api-data:
  ships-api-gems:
